#package_assets:         on          # (on, off, always)
#embed_assets:           on          # (on, off, datauri)
#compress_assets:        on          # (on, off)
#gzip_assets:            on          # (on, off)
#template_function:      _.template  # (defaults to the built-in micro-templating)
#package_path:           packages    # (defaults to assets)
#javascript_compressor:  closure     # (yui, closure)
#compressor_options:
  #compilation_level: ADVANCED_OPTIMIZATIONS

javascripts:
  main:
    - public/javascripts/jquery.js
    - public/javascripts/modernizr.js
    - public/javascripts/jquery.validation.js
    - public/javascripts/jquery.noisy.js
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  screen:
    - public/stylesheets/screen.css
  email:
    - public/stylesheets/screen.css
    - public/stylesheets/email.css
  print:
    - public/stylesheets/print.css
  ie:
    - public/stylesheets/ie.css

